[general]
import = [
  "~/.config/alacritty/catppuccin-oled.toml",
]

[window]
padding = { x = 32, y = 32 }
opacity = 0.875

[font]
normal = { family = "Cascadia Code NF", style = "Regular" }
size = 11.25

[terminal]
shell = { program = "brush", args = ["--login"] }
